import "./globals.css";

import NavLink from "@/app/nav-link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"bg-gray-900 text-white "}>
      <body>
        <header className={"border-b p-4"}>
          <nav className={"space-x-4"}>
            <NavLink href="/">Home</NavLink>
            <NavLink href="/movies">movies</NavLink>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
