import "./globals.css";

import NavLink from "@/app/nav-link";
import Header from "@/app/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"bg-gray-900 text-white"}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
